### ISSUE TITLE
helm-diff version v2.9.0+1 isn't baked into v2.9.0

### ISSUE THREAD

**Issue by jeff-knurek** [devth/helm-docker#19]
v2.9.0+1 of `helm-diff` plugin was built on 27th April
https://github.com/databus23/helm-diff/releases/tag/v2.9.0%2B1

but the `devth/helm` `v2.9.0` docker image was built on the 26th of April
https://github.com/devth/helm-docker/releases/tag/v2.9.0

this means that running `helm plugin list` in the docker image results in
```
NAME	VERSION	DESCRIPTION                                    
diff	2.8.2+2	Preview helm upgrade changes as a diff         
gcs 	0.2.0  	Provides Google Cloud Storage protocol suppo...
```

-----
This is more of an annoyance than a real bug with `devth/helm`, but I guess my suggestion is to create a new tag `v2.9.0+1` (?) which should then sync these versions.

**Comment by devth** [comment]
@jeff-knurek sorry for the slow reply. Is this fixed by the latest release? https://github.com/devth/helm-docker/issues/20

**Comment by jeff-knurek** [comment]
well, I wouldn't say it's "fixed", because the `2.9.0` image still doesn't have the latest `helm diff`, but I do think that this issue is now obsolete
